### ISSUE TITLE
static-gen.py updates every bucket

### ISSUE THREAD

**Issue by kra** [futel/usage#59] opened 2023-01-23 17:47 UTC
python src/static-gen.py

```
Walking s3 bucket content...
Checking events/prod/20211110...
events/prod/20211110 needs updating.
Got 3 events
Checking events/prod/20211112...
events/prod/20211112 needs updating.
Got 291 events
```

etc etc, every file gets touched every time I run, even running twice in a row

this is only a minor annoyance when testing but is this an issue in production?

**Comment by kra** [comment] 2023-01-23 21:58
I thought this was becuase I didn't have a data dir, but I created one and it still didn't create the json file for last update.

**Comment by breedx2** [comment] 2024-01-07 00:36
The terminology here is wrong, there's only one s3 bucket. By design, the code _is_ definitely touching the key for every day, to make sure that we didn't miss something. This is useful when the day flips over midnight, but it's also helpful when backfillling (eg. if we had to go back and mangle or rebuild stuff in s3).

I'm going to close this, but reopen if you have some ideas on how to do things differently or more specifics about what the problem actually is.

**Closed by breedx2** 2024-01-07 00:36 UTC
